### ISSUE TITLE
pretrained model and data formatting

### ISSUE THREAD

**Issue by ZhaofengWu** [tdozat/Parser-v3#4]
1. Do you have a pretrained SDP model that we can download?
2. What is the expected formatting to train an SDP model? It seems that the required fields in `conllu_vocabs.py' are different from the SemEval 2015 format (below)
![image](https://user-images.githubusercontent.com/11954789/56409635-cedb3180-622e-11e9-95f1-70a76dcd1cac.png)
3. `SemheadVocab` and `SemrelVocab` in `conllu_vocabs.py' have the same index. Is that expected?

**Comment by ZhaofengWu** [comment]
Even if I change the indices to point to the "frame" column, there is still an error
```
Traceback (most recent call last):
  File "main.py", line 284, in <module>
    main()
  File "main.py", line 107, in main
    kwargs.pop('action')(**kwargs)
  File "main.py", line 169, in train
    network.train(load=load, noscreen=noscreen)
  File "/homes/iws/lyt826/Parser-v3/parser/base_network.py", line 115, in train
    config=self._config)
  File "/homes/iws/lyt826/Parser-v3/parser/structs/conllu_dataset.py", line 230, in __init__
    super(CoNLLUTrainset, self).__init__(config.getfiles(self, 'train_conllus'), *args, config=config, **kwargs)
  File "/homes/iws/lyt826/Parser-v3/parser/structs/conllu_dataset.py", line 60, in __init__
    self.load_next()
  File "/homes/iws/lyt826/Parser-v3/parser/structs/conllu_dataset.py", line 85, in load_next
    self.add(sent)
  File "/homes/iws/lyt826/Parser-v3/parser/structs/conllu_dataset.py", line 85, in load_next
    self.add(sent)
  File "/homes/iws/lyt826/Parser-v3/parser/structs/conllu_dataset.py", line 110, in add
    indices = vocab.add_sequence(tokens) # for graphs, list of (head, label) pairs
  File "/homes/iws/lyt826/Parser-v3/parser/structs/vocabs/base_vocabs.py", line 60, in add_sequence
    return [self.add(token) for token in tokens]
  File "/homes/iws/lyt826/Parser-v3/parser/structs/vocabs/base_vocabs.py", line 60, in <listcomp>
    return [self.add(token) for token in tokens]
  File "/homes/iws/lyt826/Parser-v3/parser/structs/vocabs/index_vocabs.py", line 51, in add
    return self.index(token)
  File "/homes/iws/lyt826/Parser-v3/parser/structs/vocabs/index_vocabs.py", line 466, in index
    nodes.append(int(head))
ValueError: invalid literal for int() with base 10: 'named'
```

**Comment by TonyNemo** [comment]
Hi there, I was wondering where to find the word embeddings en.vectors.xz?
I try to train the model, using conll2018 English data, but this occurs:

```
(py36) yangyy@amax:~/SemEval/Parser-v3$ python main.py train ParserNetwork
saves/CoNLL18/English-EWT/ParserNetwork already exists. It will be deleted if you continue. Do you want to proceed? [Y/n] y
Traceback (most recent call last):
  File "main.py", line 284, in <module>
    main()
  File "main.py", line 107, in main
    kwargs.pop('action')(**kwargs)
  File "main.py", line 168, in train
    network = NetworkClass(input_networks=input_networks, config=config)
  File "/home/yangyy/SemEval/Parser-v3/parser/base_network.py", line 79, in __init__
    vocab.load() or vocab.count(self.train_conllus)
  File "/home/yangyy/SemEval/Parser-v3/parser/structs/vocabs/multivocabs.py", line 102, in count
    status = (vocab._loaded or vocab.count(train_conllus) if hasattr(vocab, 'count') else True) and status
  File "/home/yangyy/SemEval/Parser-v3/parser/structs/vocabs/pretrained_vocabs.py", line 112, in count
    with open_func(self.pretrained_file, 'rb') as f:
  File "/home/yangyy/miniconda3/envs/py36/lib/python3.6/lzma.py", line 302, in open
    preset=preset, filters=filters)
  File "/home/yangyy/miniconda3/envs/py36/lib/python3.6/lzma.py", line 120, in __init__
    self._fp = builtins.open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/word2vec/English/en.vectors.xz'

```

**Comment by qipeng** [comment]
@TonyNemo we have documented the process for downloading these word vectors here in our new `stanfordnlp` repo: https://github.com/stanfordnlp/stanfordnlp/blob/master/scripts/download_vectors.sh

Hope this helps!

**Comment by TonyNemo** [comment]
> @TonyNemo we have documented the process for downloading these word vectors here in our new `stanfordnlp` repo: https://github.com/stanfordnlp/stanfordnlp/blob/master/scripts/download_vectors.sh
> 
> Hope this helps!

Thanks for your reply! It is very helpful!
